### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 5000
}

### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### cancle balance
POST http://localhost:8080/transaction/cancle
Content-Type: application/json

{
  "transactionId": "9281b51d5fdc44d6ba57c14412084fdc",
  "accountNumber": "1000000000",
  "amount": 5000
}

### query transaction
GET http://localhost:8080/transaction/22b850d7aa18477e9508627926d696fd
Accept: application/json
